-   route-template:
        id: Route templates from fhir_sink:v4_4_3 (modified)
        from:
            uri: vantiq://server.config?consumerOutputJsonStream=true&structuredMessageHeader=true
            steps:
            -   choice:
                    precondition: true
                    when:
                    -   simple: ${properties:encoding} =~ 'JSON'
                        steps:
                        -   unmarshal:
                                fhirJson:
                                    fhirVersion: '{{fhirVersion}}'
                                    prettyPrint: '{{prettyPrint}}'
                    -   simple: ${properties:encoding} =~ 'XML'
                        steps:
                        -   unmarshal:
                                fhirXml:
                                    fhirVersion: '{{fhirVersion}}'
                                    prettyPrint: '{{prettyPrint}}'
            -   to:
                    uri: fhir://{{apiName}}/{{methodName}}
                    parameters:
                        serverUrl: '{{serverUrl}}'
                        encoding: '{{encoding}}'
                        fhirVersion: '{{fhirVersion}}'
                        log: '{{log}}'
                        prettyPrint: '{{prettyPrint}}'
                        lazyStartProducer: '{{lazyStartProducer}}'
                        proxyHost: '{{?proxyHost}}'
                        proxyPassword: '{{?proxyPassword}}'
                        proxyPort: '{{?proxyPort}}'
                        proxyUser: '{{?proxyUser}}'
                        accessToken: '{{?accessToken}}'
                        username: '{{?username}}'
                        password: '{{?password}}'
            - marshal:
                    fhirJson:
                        fhirVersion: '{{fhirVersion}}'
                        prettyPrint: '{{prettyPrint}}'
            - to:
                    uri: vantiq://server.config?consumerOutputJsonStream=true&structuredMessageHeader=true

